### ISSUE TITLE
How to increase siji size?

### ISSUE THREAD

**Issue by frank604** [drkhsh/slstatus#26]
I have very little knowledge in C and have enjoyed using slstatus.  However, with a recent upgrade to hidpi the siji glyph size are now too small.  I tried to change the header file to something like:
 static const char fonts[]= "-*-Siji-medium-r-*-*-12-*-*-*-*-*-*-*";

but this did not have any effect.  Any suggestion and/or help appreciated.  Thank you for sharing your code as well!!

**Comment by drkhsh** [comment]
Fonts are not part of slstatus. You will have to set it in DWM, as slstatus just sets the text.
Thanks! No problem.

**Comment by frank604** [comment]
Oh!!! That makes sense.  Thank you so much for that.
