### ISSUE TITLE
Feature Request: Caps/Num/Scroll Lock Indicators

### ISSUE THREAD

**Issue by Rergis** [drkhsh/slstatus#31]
I'm on a laptop without physical leds, so i've managed to write a bash script (yes, i don't know much about C yet) to see those keys when activate in my statusbar (dwm, i'm in love).

It is possible to have this in slstatus?...Man i'm only need this to finaly replace my ugly script for slstatus. Send you a photo of how ugly is it:

> #!/bin/sh
while :
value=$(xset q | grep "LED mask" | sed -r "s/.*LED mask:\s+[0-9a-fA-F]+([0-9a-fA-F]).*/\1/")
case $value in
	0)
	key="" 	;;
	1)
	key="[C]" 	;;
	2)
	key="[N]" 	;;
	3)
	key="[C] [N]" ;;
esac
do
	xsetroot -name "$key"
	sleep 0.2
done

It really sucks dude...

**Comment by drkhsh** [comment]
I can totally understand that this sucks bro... :-) I will check this out later today ok? But it seems like a nice feature.

**Comment by R41z** [comment]
you can integrate this script with run_command(), that's why it's there.

**Comment by drkhsh** [comment]
yeah, but a C solution would be nicer!

**Comment by R41z** [comment]
my point is, this gentlemen doesn't even know how to use the program, since it relies on your C knowledge to use it.

**Comment by drkhsh** [comment]
You don't have to know C to use this @R41z and I don't want people to know C for it.

@Rergis I will really implement this, as I like it. 😄

**Comment by Rergis** [comment]
Very very very....very basic approach (stolen from [here](http://stackoverflow.com/questions/8427817/how-to-get-a-num-lock-state-using-c-c) and slightly modified):

```
#include <stdio.h>
#include <X11/Xlib.h>

int main(void) {  
   Display *dpy = XOpenDisplay(":0"); 
   XKeyboardState x;
   XGetKeyboardControl(dpy, &x);
   XCloseDisplay(dpy);

   switch(x.led_mask)
   {
   case 1:
		printf("[C]");
		break;
   case 2:
		printf("[N]");
		break;
   case 3:
		printf("[C+N]");
		break;
   default:
		printf(" ");
   }
   getchar();
   return 0;
}
```

named kleds and compiled doing:
`gcc kleds.c -o kleds -lX11`

worked for my cofee machine (laptop).

**Comment by drkhsh** [comment]
@Rergis thanks, will have a look

**Comment by drkhsh** [comment]
@Rergis the problem will be the Display opening thing … Some solution without Xlib would be preferred

**Comment by Rergis** [comment]
Ok, i'll keep trying

**Comment by R41z** [comment]
is that a joke? the program itself depends on Xlib!

**Comment by drkhsh** [comment]
but display opening happens only if you enable dwm output

**Comment by R41z** [comment]
the doesn't change the fact that the program will have Xlib as a *dependency*

**Comment by R41z** [comment]
http://sprunge.us/iVfC

```
diff --git a/slstatus.c b/slstatus.c
index 89186d6..ddba063 100644
--- a/slstatus.c
+++ b/slstatus.c
@@ -64,6 +64,7 @@ static char *username(void);
 static char *vol_perc(const char *card);
 static char *wifi_perc(const char *iface);
 static char *wifi_essid(const char *iface);
+static char *kbd_indic(void);
 static void sighandler(const int signo);
 static void usage(const int eval);
 
@@ -733,6 +734,29 @@ wifi_essid(const char *iface)
 		return smprintf("%s", (char *)wreq.u.essid.pointer);
 }
 
+static char*
+kbd_indic(void)
+{
+	Display *dpy = XOpenDisplay(NULL);
+	XKeyboardState x;
+	XGetKeyboardControl(dpy, &x);
+	XCloseDisplay(dpy);
+
+	switch (x.led_mask) {
+	case 1:
+		return smprintf("[C][ ]");
+		break;
+	case 2:
+		return smprintf("[ ][N]");
+		break;
+	case 3:
+		return smprintf("[C][N]");
+		break;
+	default:
+		return smprintf("[ ][ ]");
+	}
+}
+
 static void
 sighandler(const int signo)
 {
```

**Comment by drkhsh** [comment]
Look nice @R41z, will implement it. Thanks a lot

**Comment by drkhsh** [comment]
@Rergis OK?

**Comment by Rergis** [comment]
Dude, you made me happy!. @drkhsh @R41z Thankyou!!!

**Comment by R41z** [comment]
Wait? you introduced a bug in your last commit, https://github.com/drkhsh/slstatus/commit/823f2d047f9f14c5e401c337274c8c19542b3065, this is not how my patch did it, you're trying to run XCloseDisplay() after the function returns? get it? It's NOTREACHED

**Comment by R41z** [comment]
just out of curiosity, did it crash after a while of running it? ^^

**Comment by drkhsh** [comment]
Did not see the bug in 823f2d0, sorry.

> get it? It's NOTREACHED

Please don't speak with me in such a tone OK? Be kind and friendly in my repo.

> just out of curiosity, did it crash after a while of running it? ^^

I did not test it for longer than 5 minutes …

**Comment by R41z** [comment]
how is that rude? O.o capitalizing "NOTREACHED" doesn't mean yelling.

**Comment by drkhsh** [comment]
No problem @R41z, chill dude 😄
