### ISSUE TITLE
TODO: fix build on BSD platforms

### ISSUE THREAD

**Issue by R41z** [drkhsh/slstatus#33]

**Comment by drkhsh** [comment]
Porting to BSD is huge work… Is it worth it?

**Comment by R41z** [comment]
this time it doesn't have to involve porting, we could just grab what works and have it running on openbsd, this will fix building slstatus on openbsd so I can start using it.

**Comment by drkhsh** [comment]
Hm but does that make sense?

**Comment by R41z** [comment]
of course, it would not have the same functionality it does on linux, but it will still work on bsd, that's the point, there are benefits of portability.

**Comment by R41z** [comment]
I'll work on the TODO list soon as I finish with this libreboot mess

**Comment by drkhsh** [comment]
nice

**Comment by R41z** [comment]
hey, I'm sorry because I left this behind, last two weeks I was very depressed (I'm still depressed though), I just wanted to inform you that in my tree, slstatus builds on OpenBSD now, however, it is not ready to merge, there is lots of work need to be done there (adding --<func> <args> option), could you please take a look at my tree and review the new changes? https://github.com/r41z/slstatus Oh! and by the way, I'm not using dwm anymore, so I'm not sure how the new commits work with X11 and dwm, so it would be nice if you can test that too.

**Comment by R41z** [comment]
and btw, get rid of this fucking port branch, we don't need it.

**Comment by drkhsh** [comment]
i partially applied your changes.

i would like to keep config.h and not use the --paramters for configuration.

i already deleted the port branch

**Comment by R41z** [comment]
fine then... porting to BSD actually worked, there's nothing but testing on other BSD platforms and doing small modifications probably, it's in my repo if you're interested.
