### ISSUE TITLE
mpd 'now playing'

### ISSUE THREAD

**Issue by mrneilypops** [drkhsh/slstatus#40]
This is the only feature I am missing.
Is it possible yo include in slstatus?

**Comment by R41z** [comment]
You could use the `run_command` feature, or write your own function.  I don't know how mpd works as I don't use it, but since it's a daemon, there should be some sort of an IPC somewhere.

**Comment by drkhsh** [comment]
@mrneilypops please use run_command. i will not include mpd natively.
